### ISSUE TITLE
First Aid AA IS NOT CURRENTLY WORKING

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#250]
The AA First Aid should raise max bind wound cap by 10% per rank, but it currently isn't allowing the cap to be raised over the base 50%

**Comment by mixxit** [comment]
```what class are you
what level are you
what skill level is your bind wound```

**Comment by mixxit** [comment]
This was working but you had to meet innate requirements which dont make sense with the all classes attribute of this AA

So youd have to be over level 50 and have 200 skill to see this actively working which is what we had during testing of this AA

Ive removed the check on innate bonuses so all classes can use this and before level 51 since the AA is purchasable before then - this has also been applied to the Bandage Wounds AA

Appears fixed from testing, thanks
