### ISSUE TITLE
Spells that are not coded

### ISSUE THREAD

**Issue by OEillet-Rissa** [mixxit/solinia3-core#276]
Mass Enchant Silver, Mass Enchanct Clay, Enchant Clay, Enchant Silver. Enchant Gold, Thicken Mana, Mass Enchant Electrum, Enchant Electrum, Imbue Justice.

**Comment by Ferreluke** [comment]
All enchant gem spells are currently not working. I think Mixxit had future plans for them concerning tradeskills. This is a known issue.

**Comment by mixxit** [comment]
Hi because the amount of trade skills items across clerics, enchanters and druids we cannot add these spells now, i will close this issue but you are welcome to create all the items and missing recipes

http://www.eqtraders.com/ is where you will find all the items and recipes involved if someone wants to pick this up, but i recommend you add it as a project on this website instead of an issue

thanks
